prometheus:
  prometheusSpec:
    nodeSelector: 
      purpose: monitoring

    tolerations:
      - key: "purpose"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"        

    retention: "5d"           
    retentionSize: "8GiB"   

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-path"
          accessModes: ["ReadWriteOnce"] 
          resources:
            requests:
              storage: 10Gi         
  
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
  
  service:
    type: NodePort
    nodePort: 32001 

grafana:
  nodeSelector:
    purpose: monitoring
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  
  adminPassword: "admin"
  
  persistence:
    enabled: true
    storageClassName: "local-path"
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
  deleteDatasources:
    - name: Loki
      orgId: 1

  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 1000
        derivedFields:
          - name: "TraceID"
            matcherRegex: '"trace_id":"([^"]+)"'
            url: 'http://k3s-mon.lan:32030/trace/$${__value.raw}'
            urlDisplayLabel: "Открыть в Jaeger"
      
  service:
    type: NodePort
    nodePort: 32002 

alertmanager:
  config:
    route:
      receiver: "telegram"         
      group_by: ['alertname', 'namespace']       
      group_wait: 30s       
      group_interval: 5m    
      repeat_interval: 4h
      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"

    receivers:
      - name: "null"
      - name: "telegram"
        telegram_configs:
          - bot_token: "8931700800:AAEmFRSgBt3upOd4LMNcVcwmB8G4g_0b0Bo"
            chat_id: 5477873882
            parse_mode: HTML
            send_resolved: true
            message: '{{ template "telegram.default.message" . }}'
       
  alertmanagerSpec:
    nodeSelector:
      purpose: monitoring
    tolerations:
      - key: "purpose"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "local-path"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    
  
  service:
    type: NodePort
    nodePort: 32003

prometheusOperator:
  nodeSelector:
    purpose: monitoring
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"


kube-state-metrics:
  nodeSelector:
    purpose: monitoring
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

prometheus-node-exporter:
  # сразу на всех нодах 
  tolerations:
    - operator: "Exists"


kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false 