# Jaeger, чарт jaegertracing/jaeger 4.14.0 (Jaeger v2).
# Один под: приём OTLP, хранение трейсов и веб-интерфейс.

jaeger:
  enabled: true
  replicas: 1

  nodeSelector: 
    purpose: monitoring               
  tolerations: 
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"                    
  resources: 
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "826Mi"
      cpu: "500m"
userconfig:
  service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2]
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [jaeger_storage_exporter]
    telemetry:
      resource:
        service.name: jaeger
      metrics:
        level: detailed
        readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888      

  extensions:
    healthcheckv2:
      use_v2: true
      http:
        endpoint: 0.0.0.0:13133

    jaeger_query:
      storage:
        traces: primary_store

    jaeger_storage:
      backends:
        primary_store:
          memory:
            max_traces: 50000     


  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317   
        http:
          endpoint: 0.0.0.0:4318  

  exporters:
    jaeger_storage_exporter:
      trace_storage: primary_store

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: jaeger-ui
      labels:
        app.kubernetes.io/name: jaeger
    spec:
      type: NodePort
      selector:
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: jaeger
        app.kubernetes.io/name: jaeger
      ports:
        - name: http-query
          port: 16686
          targetPort: 16686
          nodePort: 32030
