{
 "title": "RED api",
 "description": "RED",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(api_requests_total{namespace=\"lab2\"},pod)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(api_requests_total{namespace=\"lab2\", container=\"lab-api\"},path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Общие показатели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество ошибок ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(api_requests_total{status=~\"5..\", namespace=\"lab2\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Сколько запросов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (path) (increase(api_requests_total{namespace=\"lab2\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Процент ошибок относительно общего числа запросов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total{status=~\"[5]..\", namespace=\"lab2\"}[$__rate_interval])) / sum(rate(api_requests_total{ namespace=\"lab2\"}[$__rate_interval]))\n",
     "legendFormat": "Доля ошибок"
    }
   ]
  },
  {
   "title": "Запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(api_requests_total{namespace=\"lab2\", pod=~\"$pod\", path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "95 процентиль",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(api_request_duration_seconds_bucket{namespace=\"lab2\", path=~\"$path\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Логи",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"lab2\"}"
    }
   ]
  }
 ]
}